@startuml
title Exemplo
package modelo {
	class Animal
}

class Animal {
+ String especie
# double comprimento
+ Animal()
}

package modelo {
	class Carro
}

class Carro {
+ String placa
- String nome
+ Carro()
}

Animal "1..*" *-- "1..*" Carro
@enduml